### ISSUE TITLE
fe.life

### ISSUE THREAD

**Issue by htakemur** [francopestilli/life#38]
I found that the structure fe.life is removed from the newest version of feSet.m
fe.life will not be used for anymore?

I found that there are several codes which are still using fe.life, which will make bugs.

feGet.m
feConnectomeReduceFibers.m 
feConnectomeReduceVoxels.m 
feGetConnectomeInfo.m 
feConnectomeBuildModel.m

**Comment by francopestilli** [comment]
Is this issue resolved?

**Comment by arokem** [comment]
I think that none of these are show-stoppers, but there are still a few places in the code that have references to `fe.life`: 

./fe/feConnectomeBuildModel.m:
  178 :   fe.life.dSig(dense_rows) = feGet(fe,'diffusion signal in voxel',usedVoxels(vv));
./fe/feConnectomeReduceFibers.m:
   23 :     fe.life.Mfiber = sparse(size(fe.life.Mfiber,1),size(fe.life.Mfiber,2));
   26 :     fe.life.Mfiber = fe.life.Mfiber(:,fibersToKeep);
   31 : if isfield(fe.life,'fit') && ~isempty(fe.life.fit)
   32 :     fe.life.fit.weights         = fe.life.fit.weights(fibersToKeep);
   33 :     fe.life.fit.results.nParams = sum(fibersToKeep);
   35 : if isfield(fe.life,'voxfit') && ~isempty(fe.life.voxfit)
   36 :     fe.life.voxfit = [];
   40 : if isfield(fe.life,'fibers') && ~isempty(fe.life.fibers.tensors)
   41 :     fe.life.fibers.tensors = [];
   42 :     fe.life.fibers.total   = [];
   43 :     fe.life.fibers.unique  = [];
./fe/feConnectomeReduceVoxels.m:
   20 : fe.life.Mfiber = fe.life.Mfiber(vxRows,:);
   21 : fe.life.dSig   = fe.life.dSig(vxRows);
   28 : fe.life.diffusion_signal_img = fe.life.diffusion_signal_img(voxelsToKeep,:);
   31 : if ~isempty(fe.life.diffusion_S0_img)
   32 : fe.life.diffusion_S0_img = fe.life.diffusion_S0_img(voxelsToKeep);
   36 : fe.life.vovel2FNpair = [];
./fe/feConnectomeSelectFibers.m:
    6 : % The connectome select process builds the parameters inside of fe.life for
    7 : % a selected set of fibers.  The parameters inside of fe.life that are
   11 : %   The fe.life.fibers entries
   49 : % Take care of the field fe.life.fibers
   51 : if ~isempty(fe.life.fibers.tensors)
./scripts/dipy_validation.m:
   22 : weights = fe.life.fit.weights;

**Comment by arokem** [comment]
Whoops - you can ignore that last one. I only have that locally for my own validation.
